added OpenAPI specs for meroku store
merokudao/storekit pull request #1
Opened 2022-12-21 21:53 UTC by hardikdev17

2022-12-24 11:45 UTC, hardikdev17 commented
Web server with RESTful API endpoints for meroku store

2022-12-25 01:25 UTC, r4881t requested changes

2022-12-25 01:25 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +    const search: FilterOptions = req.query;
Dont think this will have the desired effect. 

How do I know?

1. Add a `console.log(search)`.
2. Make a `curl  http://localhost:8000/dapp/nft/isMatureContent=false&minAge=19` and you will see 
<img width="913" alt="Screenshot 2022-12-25 at 6 44 10 AM" src="https://user-images.githubusercontent.com/81687400/209454444-209b828c-55a0-4fd1-a4a5-d0c1214c9d9b.png">
<img width="487" alt="Screenshot 2022-12-25 at 6 44 03 AM" src="https://user-images.githubusercontent.com/81687400/209454445-7f7789e8-d338-4bc0-b31f-7b79c49e6b20.png">


Solution - https://expressjs.com/en/api.html#req.param

Use the abobe.

Your request should look like below: 

http://localhost:8000/dapps?search=SEARCH_TEXT&param1=value1&param2=value2&param3=value3&param3=value4 (Note that duplicate value of param3 is not error). ref to https://masteringjs.io/tutorials/express/query-parameters for passing arrays.

Once you get these values, you need to reconstruct the filteropts

Like below


```typescript


let filterOpts: FilterOptions = {};

if (req.param('availableOnPlatform')) {
  filterOpts.availableOnPlatform = req.param('availableOnPlatform')
}

```

and so on for all the options defined at https://github.com/merokudao/dapp-store-registry/blob/main/src/interfaces/filterOptions.ts

2022-12-25 01:25 UTC, r4881t commented on apps/server/package.json
> +    "@merokudao/dapp-store-registry": "0.1.2",
Use 0.1.5

2022-12-25 01:25 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +    const name: string = req.params.name;
Thou shalt not use `req.params` for such stuff. These are passed as POST and the params are not for this use case REF: https://expressjs.com/en/api.html#req.params

You need something like https://codeforgeek.com/handle-get-post-request-express-4/

2022-12-25 01:26 UTC, r4881t commented
keep your turbo.json like below so that you can use `yarn start:dev`


**turbo.json**

```json
{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**"]
    },
    "lint": {
      "outputs": []
    },
    "dev": {
      "cache": false
    },
    "start:dev": {
      "cache": false
    }
  }
}

```


**package.json**

```json
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev --parallel",
    "lint": "turbo run lint",
    "format": "prettier --write \"**/*.{ts,tsx,md}\"",
    "start:dev": "turbo run start:dev"
  },

```

2022-12-25 01:26 UTC, r4881t commented
Also, check the APIs by making appropriate CURL calls. You will get the curl commands from the OpenAPI spec

2022-12-25 05:47 UTC, r4881t requested changes

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +      summary: For updating the exisitng dapp
Replace with "Update dApp"

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +          application/xml:
Are you really planning to accept XML format? or JSON? We should NOT support them. We should support only application/x-www-form-urlencoded format in the body of the request. So please remove other formats from this API and any other API endpoint.

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +            application/xml:
We are NOT going to support XML format as response format. Only JSON response format is supported, so remove this format from this and any other API call.

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +      summary: For listing new Dapp to the store
Replace with "Add dApp"

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +          in: header
This should NOT be in header. This should be `in: query`

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +        - name: search
I don't think this is how you specify multiple options in the query param. You should create one for each, ex: 


```yaml

        - in: query
          name: isListed
          required: false
          schema:
            type: boolean
          description: DESC
        - in: query
          name: language
          required: false
          schema:
            type: string
          description: SOME DESC
```

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +  /dapp/featured:
This should be `/store/featured` as this is valid for dApp Store and not the dApp

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +  /dapp/title/:
This should be `/store/title` as this is valid for dApp Store and not the dApp

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +      summary: For deleteing the dapp in the store
replace with "Delete dApp"

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +              $ref: '#/components/schemas/Dapp'
This should be replaced with another schema which also includes the developer's details. Maybe call it `DappWithDevCreds` or something similar

Other fields to be added
-  email: string: The email that we get from Github about logged In user
-  accessToken: string: The JWT access token for user-server request
-  githubID: string: The github username of the logged in user
-  org: string: Optional. The org that the user is acting on behalf of. Comes from github org

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +      parameters:
The parameters should be in www-url-encoded and should also contain the fields like email: string: The email that we get from Github about logged In user
accessToken: string: The JWT access token for user-server request
githubID: string: The github username of the logged in user
org: string: Optional. The org that the user is acting on behalf of. Comes from github org as mentioned at https://github.com/merokudao/dapp-store-registry/blob/8175448cf32120b30c10d107adc15cbc8c017657/src/lib/registry.ts#L410

2022-12-25 05:47 UTC, r4881t commented on open-api-specs.yaml
> +              $ref: '#/components/schemas/Dapp'
This should be replaced with another schema which also includes the developer's details. Maybe call it `DappWithDevCreds` or something similar

Other fields to be added
-  email: string: The email that we get from Github about logged In user
-  accessToken: string: The JWT access token for user-server request
-  githubID: string: The github username of the logged in user
-  org: string: Optional. The org that the user is acting on behalf of. Comes from github org

2022-12-26 10:17 UTC, r4881t requested changes

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +      if (req.query.isMatureContent) {
<img width="957" alt="Screenshot 2022-12-26 at 3 31 02 PM" src="https://user-images.githubusercontent.com/81687400/209535633-f828e7f8-9139-4eee-a9c8-f9bebd25031d.png">


You see the type of `req.query.isMatureContent` in screenshot above. So if it is defined (by checking `if (req.query.isMatureContent)` then you are setting the `filterOpts.forMatureAudience` to `true`. This is incorrect.

You would have to (a) check if `req.query.isMatureContent` is defined (b) parse it into boolean and then set the params accordingly.


```typescript

if (req.query.isMatureContent) {
  filterOpts.forMatureAudience = req.query.isMatureContent === 'true' ? true : false;
}

```

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.minAge = parseInt(minAge);
`parseInt` or any parse function should always be within a local try/catch block.

Reason: Your user can send a string that may or may not get parsed into Integer.

For example if user send `minAge` as "twenty" then the above Line 29 will throw exception.

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.chainId = parseInt(<string>req.query.chainId);
local try/catch block

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.availableOnPlatform = tmp.split(",");
It's also a good idea to trim (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) the string before sending/using it

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.listedOnOrAfter = new Date(
1. use `parseISO` example https://github.com/merokudao/dapp-store-registry/blob/8175448cf32120b30c10d107adc15cbc8c017657/src/lib/registry.ts#L5
2. Also local try/catch block

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.listedOnOrBefore = new Date(<string>req.query.minAge);
Same as above

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.allowedInCountries = tmp.split(",");
trim

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.blockedInCountries = tmp.split(",");
trim

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.categories = tmp.split(",");
trim

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.isListed = true;
same changes as for  `req.query.isMatureContent`

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +        filterOpts.developer.githubID = <string>req.query.developer;
trim

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +      const response: DAppSchema[] = DappStore.search(
1. "search string" should be a part of query param
2. Here you should call the [getDapps](https://github.com/merokudao/dapp-store-registry/blob/8175448cf32120b30c10d107adc15cbc8c017657/src/lib/registry.ts#L334) if `req.params.search` is empty. If it is not then call [search](https://github.com/merokudao/dapp-store-registry/blob/8175448cf32120b30c10d107adc15cbc8c017657/src/lib/registry.ts#L506).

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/routes.ts
> +routes.get("/dapp/:search", DappRegistoryController.getDapps);
This should be in the following format

- /dapp
- /dapp?search=QUERY_STRING_HERE

So change it from path param to query param

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/server.ts
> +const PORT = 8000;
Take the port value from environment variable with default to 8000

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/server.ts
> +app.listen(8000, ()=>{
Whats the point of defining PORT in Line4 if you are using a hard coded value here?

2022-12-26 10:17 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +  addDapp = async (req: Request, res: Response) => {
Since all the parameters in this request are mandatory (except organization), you should use something like https://express-validator.github.io/docs/ to ensure that the validation happens even before the control is passed to underlying function

2022-12-26 16:52 UTC, r4881t requested changes

2022-12-26 16:52 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +      if (search == undefined) {
Couple of things

1. Use `===` instead of `==`.
2. Here, if your use case is to simply check if `search` is undefined or empty string, you can do 

```typescript


if (search && search.trim() !== '' ) {
 // do search
} else {
 // do getDapps
}
```

2022-12-26 16:52 UTC, r4881t commented on apps/server/src/routes.ts
> +routes.put("/dapp", DappRegistoryController.updateDapp);
This should also have the same validation as `POST /dapp`

2022-12-26 16:52 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +      utils.writeJson(res, e);
This should send response code of 400 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400. 

Two options

1. You will need to update the second param that is being passed to writeJson.
2. Or you use standard expressJs response response something on the lines of https://stackoverflow.com/a/57640319/229341

This applies to everywhere you are catching an error and sending the error to user via response.

2022-12-26 16:52 UTC, r4881t commented on apps/server/src/controllers/dappRegistoryController.ts
> +          console.error(e);
Instead of `console.*` functions, you should use npm package debug https://www.npmjs.com/package/debug


```typescript

import { Debug } from 'debug`;

const debug = Debug('meroku:server`);


// Now where ever you want to use console.* you can do

debug('My Log Message')

// or

try { 
// something
}
catch (err) {
  debug(e.message)
}

```

2022-12-26 18:30 UTC, hardikdev17 commented on apps/server/src/controllers/dappRegistoryController.ts
> +      utils.writeJson(res, e);
I am sending the writeJson function it already has the code parameter if I pass the third attribute in writeJson as the status code it should work... what do you think?

Else, I can remove this writeJson thing and use this everywhere
res.status(status_code).send(message)

`writeJson file`
var ResponsePayload = function(code, payload) {
  this.code = code;
  this.payload = payload;
}

exports.respondWithCode = function(code, payload) {
  return new ResponsePayload(code, payload);
}

var writeJson = exports.writeJson = function(response, arg1, arg2) {
  var code;
  var payload;

  if(arg1 && arg1 instanceof ResponsePayload) {
    writeJson(response, arg1.payload, arg1.code);
    return;
  }

  if(arg2 && Number.isInteger(arg2)) {
    code = arg2;
  }
  else {
    if(arg1 && Number.isInteger(arg1)) {
      code = arg1;
    }
  }
  if(code && arg1) {
    payload = arg1;
  }
  else if(arg1) {
    payload = arg1;
  }

  if(!code) {
    // if no response code given, we default to 200
    code = 200;
  }
  if(typeof payload === 'object') {
    payload = JSON.stringify(payload, null, 2);
  }
  response.writeHead(code, {'Content-Type': 'application/json'});
  response.end(payload);
}

2022-12-27 18:55 UTC, r4881t requested changes

2022-12-27 18:55 UTC, r4881t commented on apps/server/open-api-specs.yaml
> +    delete:
Imp note: The HTTP DELETE call implementation strips out the body at times. In ExpressJS we have observed this behaviour previously. 


To resolve this, there are two ways
1. Send the auth info in headers. Ex: in this case, the githubAuth Token, githubID, email should be encrypted/encoded and sent back to the server. This will remove these payload from the body of the request
2. Create another call `POST /deletedApp` that will take these params in request body and perform delete.


From a purist HTTP RESTful CRUD API perspective, option 1 makes more sense. But from an implementation perspective it doesn't matter.

So I leave it upto you to choose an option and change the api spec here, and the implementation.

2022-12-27 18:55 UTC, r4881t commented on apps/server/open-api-specs.yaml
> +      type: object
Also mention the mandatory params with the `required` property.

2022-12-27 18:55 UTC, r4881t commented on apps/server/open-api-specs.yaml
> +          required: true
This is an optional param.

2022-12-27 18:55 UTC, r4881t commented on apps/server/open-api-specs.yaml
> +        - Dapp Registry
The tag should be `Store Registry`

2022-12-28 05:02 UTC, r4881t requested changes

2022-12-28 05:02 UTC, r4881t commented on apps/server/open-api-specs.yaml
> +          type: string
Add a one liner `description` about this field. In this case, it could be **Name of the developer (from Github)**. You can take the `description` from the specification at https://github.com/merokudao/dapp-store-registry/blob/8175448cf32120b30c10d107adc15cbc8c017657/src/lib/registry.ts#L351

2022-12-28 10:58 UTC, r4881t approved these changes

2022-12-28 10:58 UTC, merged