file uploads to aws-S3
merokudao/storekit pull request #16
Opened 2023-01-19 06:36 UTC by hardikdev17

2023-01-19 14:40 UTC, r4881t requested changes
also add the updates to openapi spec file

2023-01-19 14:40 UTC, r4881t commented on apps/server/src/controllers/dappFileUploadController.ts
> +            Key: `${dappID}/${field}-${i}.png`,
Can we detect the file type instead of specifying `png`?

2023-01-19 14:40 UTC, r4881t commented on apps/server/src/controllers/dappFileUploadController.ts
> +      const url = s3.getSignedUrl("getObject", {
here during it merge it seems like you have removed the `main` changes. In this case, keep the `getBuildDownloadPreSignedUrl` implementation

2023-02-06 09:06 UTC, VanxhBitpack approved these changes
LGTM, have you tested it?

2023-02-06 09:06 UTC, VanxhBitpack commented
Resolve merge conflicts

2023-02-07 11:02 UTC, hardikdev17 commented
Yes, I have tested it. I will resolve the merge conflicts and merge it

2023-02-07 15:19 UTC, VanxhBitpack approved these changes

2023-02-07 15:31 UTC, VanxhBitpack approved these changes

2023-02-07 15:31 UTC, merged